### Registro de usuario
@baseUrl = http://localhost:3000
# @name postLogin
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "123456"
}

# > {%
#     client.global.set("auth_token", response.body.token);
# %}

@token = {{postLogin.response.body.token}}

### INICIO DE SESIÓN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "123456"
}

### RUTAS PROTEGIDAS - REEMPLAZAR TOKEN
GET {{baseUrl}}/api/users/profile HTTP/1.1
Authorization: Bearer {{token}}