### Enviar un mensaje a la IA (ASEGURAR AUTENTICACIÓN y USAR UN TOKEN VÁLIDO)
POST http://localhost:3000/api/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZGE5N2Q2NS1iZmJjLTQ4NGYtYmY4OC1jNGRiYzFiNDMzM2EiLCJpYXQiOjE3Mzg3MDM4NzIsImV4cCI6MTczOTMwODY3Mn0.Nc5afB77XgzoILr6i-mKR9sdDTwKSXcrYSPhtY89y14

{
    "model": "deepseek-r1:1.5b",
    "messages": [
        {
            "role": "user",
            "content": "¿Cuál es el significado de la vida?"
        }
    ]
}