### Enviar un mensaje a la IA (ASEGURAR AUTENTICACIÓN y USAR UN TOKEN VÁLIDO)
@baseUrl = http://localhost:3000
# @name postChat
POST {{baseUrl}}/api/chat
Content-Type: application/json
Authorization: Bearer {{}}

{
    "model": "deepseek-r1:1.5b",
    "messages": [
        {
            "role": "user",
            "content": "¿Cuál es el significado de la vida?"
        }
    ]
}

### ELIMINAR EL CHAT (TOKEN REQUERIDO)
DELETE {{baseUrl}}/api/chat/history
Authorization: Bearer {{token}}